import type { Metadata } from 'next'

// 404 shell. Replaces dist/404.html previously generated by prerender.mjs.
// noindex prevents the soft-404 avalanche pattern that SEO audit V2 (B1)
// closed in the Vite era — kept here as a structural invariant.
export const metadata: Metadata = {
  title: 'Not found',
  robots: { index: false, follow: false },
}

export default function NotFound() {
  return (
    <main>
      <h1>Not found</h1>
      <p>That page does not exist.</p>
    </main>
  )
}
