"""Application constants to prevent magic numbers and improve code readability."""

# HTTP Status Codes
HTTP_STATUS_OK = 200
HTTP_STATUS_CREATED = 201
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_UNAUTHORIZED = 401
HTTP_STATUS_FORBIDDEN = 403
HTTP_STATUS_NOT_FOUND = 404
HTTP_STATUS_UNPROCESSABLE_ENTITY = 422
HTTP_STATUS_INTERNAL_SERVER_ERROR = 500
HTTP_STATUS_NOT_IMPLEMENTED = 501

# Default values
DEFAULT_CHECK_INTERVAL_SECONDS = 3600  # 1 hour
DEFAULT_SHORT_INTERVAL_SECONDS = 600  # 10 minutes
DEFAULT_FREQUENT_INTERVAL_SECONDS = 300  # 5 minutes
DEFAULT_INFREQUENT_INTERVAL_SECONDS = 1800  # 30 minutes
DEFAULT_RARELY_INTERVAL_SECONDS = 7200  # 2 hours
DEFAULT_VERY_FREQUENT_INTERVAL_SECONDS = 60  # 1 minute
DEFAULT_QUICK_CHECK_INTERVAL_SECONDS = 120  # 2 minutes

# Comparison thresholds
MIN_EMBEDDINGS_FOR_COMPARISON = 2

# Common IDs for testing
TEST_ID_1 = 1
TEST_ID_2 = 2
TEST_ID_5 = 5
